### ISSUE TITLE
Link para o Relatório Detalhado

### ISSUE THREAD

**Issue by rafael-perini** [OrangeTesting00/orange-testing#1]
Após a execução das tarefas, atualmente, é colocado no console um json com dados da execução, inclusive senhas utilizadas no processo, como mostra o print abaixo:

![image](https://user-images.githubusercontent.com/29079104/201090350-41612bea-cf21-4d88-b7bd-1e617313059e.png)

Ao invés dessas informações, ajudaria muito se fosse apresentado somente o link para o o relatório detalhado, gerado por essa tarefa.
Exemplo: https://_instance_.orangetesting.com/reports/_XX_

![image](https://user-images.githubusercontent.com/29079104/201090756-7123b2ef-5ca9-4f81-959f-793f636d2e22.png)

**Comment by OrangeTesting00** [comment]
Aplicado.
