### ISSUE TITLE
Melhoria no README

### ISSUE THREAD

**Issue by rafael-perini** [OrangeTesting00/orange-testing#2]
Acrescentar ao README instruções para instalação, configuração do json e execução na CI.
Seriam mais ou menos as informações que vimos na apresentação:

![image](https://user-images.githubusercontent.com/29079104/201091776-9051c8fb-bd7c-4593-b733-b1bf527c2329.png)
![image](https://user-images.githubusercontent.com/29079104/201092002-80356188-d9c6-4441-b1e8-82a3892b3592.png)
![image](https://user-images.githubusercontent.com/29079104/201092117-34ab540c-4c4b-495e-9615-d16bfd02578b.png)

*Lembrando que a instalação deve utilizar a flag `-D`, para adicionar a CLI nas `devDependencies`*

**Comment by OrangeTesting00** [comment]
Aplicado.
