### ISSUE TITLE
Parâmetros por Linha de Comando

### ISSUE THREAD

**Issue by rafael-perini** [OrangeTesting00/orange-testing#5]
Permitir passar alguns argumentos a mais pela linha de comando, como token de autenticação (`--token MEU_TOKEN_AQUI`) ou URL para execução (`--url https://minha.aplicacao.com`).

Exemplo de como poderia ficar o comando final: `orangetesting --token MEU_TOKEN_AQUI --url https://minha.aplicacao.com`

**Comment by OrangeTesting00** [comment]
Aplicado.
